"""empty message

Revision ID: 82fb05eacad3
Revises: aa88b97e9cd0
Create Date: 2021-10-04 21:52:47.852201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fb05eacad3'
down_revision = 'aa88b97e9cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('sub_sub_category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('imageURL', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('tag', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('categories_id', 'product_id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('size', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('regular_price', sa.Float(), nullable=True),
    sa.Column('onsale', sa.Boolean(), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant')
    op.drop_table('product_categories')
    op.drop_table('product')
    op.drop_table('categories')
    # ### end Alembic commands ###
